name: PW Skills Overwatch Deployment - Production

on:
  push:
    branches: ["main"]

jobs:
  sentinel-deploy:
    runs-on: (runner-name)
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Compose Up
        run: sudo docker compose -f docker-compose-prod.yml up --build -d

      - name: Docker System Prune to Remove Old Images
        run: sudo docker system prune -f
